name: nordic_dfu_example
description: Demonstrates how to use the nordic_dfu plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ">=1.15.0"
  file_picker: ">=8.0.2"
  flutter:
    sdk: flutter
  flutter_blue_plus: ">=1.32.4 <1.40.0"
  nordic_dfu:
    path: ../
  permission_handler: ">=10.4.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=2.1.2"

flutter:
  uses-material-design: true

#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/file.zip
